
def get_settings(experiment_name):
        experiments = {     
            "exp_2/exp_200": {
                "PREDICTOR_VAR": 'SLP',
                "PREDICTAND_VAR": 'NAO',
                "REGION_TOR": 'north_atlantic',
                "REGION_TAND": 'north_atlantic',
                "training_ens": (1,2,3,4,5,6,7),
                "validation_ens": (8,9),
                "testing_ens": (0),
                "train_list": '1234567',
                "val_list": '89',
                "train_val_list": '123456789',
                "lead": 14,
                "days_average": 1,
                "GLOBAL_SEED": 147483648,
                "HIDDENS": [128],
                "DROPOUT": 0.5,
                "RIDGE1": 0.1,            
                "LR_INIT": 1.6182195397540547e-05,
                "BATCH_SIZE": 32,
                "RANDOM_SEED": [6, 26, 19, 54, 68],
                "act_fun": "relu",
                "N_EPOCHS": 10000,
                "PATIENCE": 25,
               # "CLASS_WEIGHT": {0 : 1, 1 : 3},
            },     
            "exp_2/exp_201": {
                "PREDICTOR_VAR": 'SLP',
                "PREDICTAND_VAR": 'NAO',
                "REGION_TOR": 'north_atlantic',
                "REGION_TAND": 'north_atlantic',
                "training_ens": (2,3,4,5,6,7,8),
                "validation_ens": (0,9),
                "testing_ens": (1),
                "train_list": '2345678',
                "val_list": '09',
                "train_val_list": '023456789',
                "lead": 14,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_2/exp_202": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 14,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_2/exp_203": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 14,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_2/exp_204": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 14,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },   
           "exp_3/exp_300": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 21,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_3/exp_301": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 21,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_3/exp_302": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 21,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_3/exp_303": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 21,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_3/exp_304": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 21,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_4/exp_400": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 28,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_4/exp_401": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 28,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_4/exp_402": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 28,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_4/exp_403": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 28,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_4/exp_404": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 28,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_5/exp_500": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 35,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_5/exp_501": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 35,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_5/exp_502": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 35,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_5/exp_503": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 35,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_5/exp_504": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 35,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [128],
               "DROPOUT": 0.5,
               "RIDGE1": 0.1,            
               "LR_INIT": 1.6182195397540547e-05,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_6/exp_600": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 42,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_6/exp_601": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 42,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_6/exp_602": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 42,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_6/exp_603": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 42,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_6/exp_604": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 42,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_7/exp_700": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 49,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_7/exp_701": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 49,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_7/exp_702": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 49,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },       
           "exp_7/exp_703": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 49,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },          
           "exp_7/exp_704": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 49,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_8/exp_800": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (1,2,3,4,5,6,7),
               "validation_ens": (8,9),
               "testing_ens": (0),
               "train_list": '1234567',
               "val_list": '89',
               "train_val_list": '123456789',
               "lead": 56,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,            
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_8/exp_801": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (2,3,4,5,6,7,8),
               "validation_ens": (0,9),
               "testing_ens": (1),
               "train_list": '2345678',
               "val_list": '09',
               "train_val_list": '023456789',
               "lead": 56,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_8/exp_802": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (3,4,5,6,7,8,9),
               "validation_ens": (0,1),
               "testing_ens": (2),
               "train_list": '3456789',
               "val_list": '01',
               "train_val_list": '013456789',
               "lead": 56,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_8/exp_803": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,4,5,6,7,8,9),
               "validation_ens": (1,2),
               "testing_ens": (3),
               "train_list": '0456789',
               "val_list": '12',
               "train_val_list": '012456789',
               "lead": 56,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
           "exp_8/exp_804": {
               "PREDICTOR_VAR": 'SLP',
               "PREDICTAND_VAR": 'NAO',
               "REGION_TOR": 'north_atlantic',
               "REGION_TAND": 'north_atlantic',
               "training_ens": (0,1,5,6,7,8,9),
               "validation_ens": (2,3),
               "testing_ens": (4),
               "train_list": '0156789',
               "val_list": '23',
               "train_val_list": '012356789',
               "lead": 56,
               "days_average": 1,
               "GLOBAL_SEED": 147483648,
               "HIDDENS": [160, 192],
               "DROPOUT": 0.8,
               "RIDGE1": 0.01,
               "LR_INIT": 2.8864337224315965e-06,
               "BATCH_SIZE": 32,
               "RANDOM_SEED": [6, 26, 19, 54, 68],
               "act_fun": "relu",
               "N_EPOCHS": 10000,
               "PATIENCE": 25,
              # "CLASS_WEIGHT": {0 : 1, 1 : 3},
           },     
       }

        return experiments[experiment_name]